### ISSUE TITLE
New Deltas reset delta count

### ISSUE THREAD

**Issue by ansuz07** [hallidev/delta-bot-four#3] opened 2018-06-29 14:23 UTC
Looking at this user:

https://www.reddit.com/r/changemyview/comments/8usrp9/cmv_if_minority_languages_are_not_mandatory_in/e1hw06a/

They have multiple deltas issued, but the new deltas are all getting recorded as their first delta issued.

**Comment by hallidev** [comment] 2018-06-29 17:22
I switched from live listing streams to traditional polling. The listing streams seem to either be unreliable or there's a bug in RedditSharp.

I am going to deploy this tonight and will close this issue if reliability improves over the next few days.

3ac7fd49108964f376c527e06ec1733df63f4968

**Comment by hallidev** [comment] 2018-06-29 17:36
I'm unsure of exactly what's happening, but my initial thought is that the delta symbol in their flair is a symbol that was used early on. I've improved the flair logic in hopes of correcting this.

The change will be deployed tonight. Please keep an eye out for a recurrence going forward and post back here to notify me that it wasn't fixed. I'll update this comment when my fix is deployed.

59adc63a5ece35676a4bddfd1e693eddf2de82a3

**Comment by hallidev** [comment] 2018-06-30 22:30
I've deployed a fix here where flair is calculated and set from the user wikis rather than existing flair. This appears to have been caused by users who had their flair set to hidden for the subreddit. DeltaBot was using user's flair to get a current delta count, increment it, and set it again. When flair was hidden, it wasn't finding a number and was resetting it to 1. I am going to close this issue. If it re-occurs, please create a new issue.

**Closed by hallidev** 2018-06-30 22:30 UTC
