### ISSUE TITLE
DB acting up again

### ISSUE THREAD

**Issue by hacksoncode** [hallidev/delta-bot-four#12] opened 2018-07-18 21:43 UTC
It hasn't been awarding deltas today... just 3 rejections spaced out across 24 hours. 

And it hasn't been responding to my PMs, either. Example: https://www.reddit.com/r/changemyview/comments/8zu4wr/cmv_ghostwriting_should_be_illegal/e2lgjf9/

I sent a PM twice about that, no response. 

Did we ever get it working on the production server, BTW?

**Comment by hallidev** [comment] 2018-07-18 22:37
Reddit seems to have pushed an update to their API that is returning slightly different json for sidebar widgets in the site redesign.

I've just pushed a fix that I hope resolves this. The bot was also crashing on the /DB4 test sub, so it was definitely something changed in the Reddit API rather than a subreddit setting on r/changemyview.

I'll watch while the first delta comes in to confirm that deltas are being awarded properly. This was causing private messages to crash as well.

If you re-send the private messages, they should process now

**Comment by hallidev** [comment] 2018-07-18 22:39
I just saw a delta get awarded properly. so the fix appears to be working

**Comment by hallidev** [comment] 2018-07-18 23:58
I'm going to close out this issue as it was the cause of the failures. It seems to be responding properly now. There are still some reliability improvements to be made on comments on private messages, but they are unrelated to this issue.

**Closed by hallidev** 2018-07-18 23:58 UTC
